
services:
  mysql:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=empresa
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_crud_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_crud_data: